version: 2
jobs:
  build:
    docker:
      - image: cimg/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies & Platform
          command: . build/install.sh
      - run:
          name: Run Build
          command: . build/build.sh
 
workflows:
  version: 2
  validate:
    jobs:
      - build:
